apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: wwwroot
          mountPath: /app/wwwroot/
        - name: conf-d
          mountPath: /etc/nginx/conf.d
        - name: conf
          mountPath: /etc/nginx/nginx.conf
      volumes:
      - name: wwwroot
        hostPath:
          path: /mnt/wwwroot
      - name: conf-d
        hostPath:
          path: /conf/conf.d
      - name: conf
        hostPath:
          path: /conf/nginx.conf
